//
//  MockAchievementViewController.swift
//  StashInvest
//
//  Created by Chanick Park on 1/14/21.

//
//  This file was generated by the 🐍 VIPER generator
//

@testable import StashInvest

final class MockAchievementViewController {

    // MARK: - Public properties -

    var presenter: MockAchievementPresenterInterface!

    enum ViewStatus {
        case none
        case waiting
        case done
    }

    var currStatus: ViewStatus = .none

    // MARK: - Lifecycle -

    func viewDidLoad() {
        currStatus = .waiting
        presenter.viewDidLoad()
    }

}

// MARK: - Extensions -

extension MockAchievementViewController: MockAchievementViewInterface {
    // Update Achievement Data
    func updateData(_ title: String) {
        currStatus = .done
    }
}
