//
//  AchievementInteractor.swift
//  StashInvest
//
//  Created by Chanick Park on 1/12/21.

//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class AchievementInteractor: AchievementInteractorInterface {
    var title: String?

    var achievements: [Achievement]?

    // Create Network manager with NetworkClient
    var achievementNetworkManager = AchievementNetworkManager(client: StashNetworkClient())
}

// MARK: - Extensions -

extension AchievementInteractor {

    // MARK: - Network request
    func retrieveAchievement(_ complete: @escaping (_ error: NetworkError?) -> Void) {
        self.achievementNetworkManager.retrieveAchievementList { (title, result) -> Void in
            switch result {
            case .success(let achievements):

                self.title = title
                self.achievements = achievements
                complete(nil)

            case .failure(let errors):
                complete(NetworkError.error(errors))
            }
        }
    }
}
