//
//  AchievementInterfaces.swift
//  StashInvest
//
//  Created by Chanick Park on 1/12/21.

//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// Move to detail view
enum AchievementNavigationOptions {
    case detail(Achievement)
}

protocol AchievementWireframeInterface: WireframeInterface {
    // Route
    func navigate(to option: AchievementNavigationOptions)
}

protocol AchievementViewInterface: ViewInterface {
    // Update view
    func updateData(_ title: String)
}

protocol AchievementPresenterInterface: PresenterInterface {
    // Access to Achievement data
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> Achievement?
    func didSelectItem(at indexPath: IndexPath)
}

protocol AchievementInteractorInterface: InteractorInterface {
    // Communicate with network module
    func retrieveAchievement(_ complete: @escaping (_ error: NetworkError?) -> Void)

    // Title
    var title: String? { get }

    // Data
    var achievements: [Achievement]? { get }
}
