//
//  ViewInterface.swift
//  StashInvest
//
//  Created by Chanick Park on 1/12/21.

//
//  This file was generated by the 🐍 VIPER generator
//
protocol ViewInterface: class {
}

extension ViewInterface {
}
